#!/usr/bin/env python3
"""Bind submitted bytes to Lean constants without executing candidate code."""
from __future__ import annotations

import argparse
from pathlib import Path

PROGRAMS = ('keygen', 'sign', 'expand', 'verify')
MAX_PROGRAM_BYTES = 1 << 20
IMAGE_FILES = {f'images/{program}.{part}' for program in PROGRAMS for part in ('code', 'data')}


def load_images(root: Path) -> dict[str, tuple[bytes, bytes]]:
    images = {}
    directory = root / 'images'
    if directory.is_symlink() or not directory.is_dir():
        raise ValueError('images/ must be a directory containing all four code/data pairs')
    for program in PROGRAMS:
        parts = []
        for part in ('code', 'data'):
            path = directory / f'{program}.{part}'
            if path.is_symlink() or not path.is_file():
                raise ValueError(f'{path.name}: a regular image file is required')
            with path.open('rb') as stream:
                raw = stream.read(MAX_PROGRAM_BYTES)
            if len(raw) >= MAX_PROGRAM_BYTES:
                raise ValueError(f'{program}: image must be smaller than 1 MiB')
            parts.append(raw)
        code, data = parts
        if len(code) % 4:
            raise ValueError(f'{program}.code: expected little-endian 32-bit instruction words')
        if len(code) + len(data) >= MAX_PROGRAM_BYTES:
            raise ValueError(f'{program}: image must be smaller than 1 MiB')
        images[program] = (code, data)
    return images


def lean_list(values: list[int]) -> str:
    # Balanced concatenation keeps parser/elaborator depth bounded for large images.
    chunks = ['[' + ', '.join(map(str, values[i:i + 128])) + ']'
              for i in range(0, len(values), 128)] or ['[]']
    while len(chunks) > 1:
        chunks = [f'({chunks[i]} ++ {chunks[i + 1]})' if i + 1 < len(chunks) else chunks[i]
                  for i in range(0, len(chunks), 2)]
    return chunks[0]


def render(images: dict[str, tuple[bytes, bytes]]) -> str:
    lines = ['-- Generated by verifier/images.py from the submitted image files.',
             'import SigGolf.Programs', '', 'set_option maxRecDepth 4096',
             'set_option maxHeartbeats 0', '', 'namespace SigGolf.Images', '']
    for program in PROGRAMS:
        code, data = images[program]
        words = [int.from_bytes(code[i:i + 4], 'little') for i in range(0, len(code), 4)]
        lines.extend([f'def {program} : Riscv.Image :=',
                      f'  {{ code := {lean_list(words)},',
                      f'    data := {lean_list(list(data))} }}', ''])
    lines.extend(['def images : Program → Riscv.Image',
                  *[f'  | .{program} => {program}' for program in PROGRAMS],
                  '', 'end SigGolf.Images', ''])
    return '\n'.join(lines)


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('submission', type=Path)
    parser.add_argument('--output', type=Path, default=Path('SigGolf/Images.lean'))
    args = parser.parse_args()
    args.output.write_text(render(load_images(args.submission)))
