"""Assemble the compact candidate's cache-assisted signing image."""

from examples.sphincs.build_images import (
    ANSWER, BASE, BIT, Builder, CACHE, CHAIN, CHAINS, COUNT, CURRENT, DIGITS,
    ENDPOINTS, FTS_HEIGHT, FTS_TREES, HASH, HEIGHTS, INDEX, LAYER, LEAF,
    LEAVES, LEVEL, MSG_INDEX, NEXT_BASE, NODE, POS, PTR, PUBLIC_KEY,
    ROOTS, SECRET_KEY, SIGNATURE, STEP, SUM, T, TREE, VALUE, layer,
    message_index,
)

TREE_CACHE = 0x50000
TREE_ROOT = 0x53000
TRIAL, SIG_PTR, SELECTED, LAST_LEAF, COUNTER, PATH_BASE, TARGET = (
    0x43098, 0x430a0, 0x430a8, 0x430b0, 0x430b8, 0x430c0, 0x430c8)


def mul20(a: Builder, result: int, value: int) -> None:
    a.shift(result, value, 2)
    a.shift(11, value, 4)
    a.add(result, result, 11)


def mul40(a: Builder, result: int, value: int) -> None:
    a.shift(result, value, 3)
    a.shift(11, value, 5)
    a.add(result, result, 11)


def compare16(a: Builder, left: int, right: int) -> None:
    a.li(6, left)
    a.li(7, right)
    for offset in (0, 8):
        a.ld(10, 6, offset)
        a.ld(12, 7, offset)
        a.reject_if_different(10, 12)


def prepare(a: Builder) -> None:
    a.variable_header(0, 0, 0, 0)
    a.cp(SECRET_KEY, HASH + 40, 32)
    a.hash(5, 72, with_parameter=False)
    a.compare20(ANSWER, CACHE + 20)
    a.cp20_fixed(CACHE, HASH + 20)
    a.cp20_fixed(CACHE + 20, HASH + 40)
    a.hash(13, 60, with_parameter=False)
    compare16(a, ANSWER, PUBLIC_KEY)
    a.cp20_fixed(CACHE, SIGNATURE)
    a.cp20_fixed(CACHE + 20, SIGNATURE + 20)


def grind(a: Builder) -> None:
    a.set(TRIAL, 0)
    a.label('grind')
    a.load(6, TRIAL)
    a.save(6, POS)
    a.set(INDEX, 0)
    a.cp(SECRET_KEY, HASH + 40, 32)
    a.cp(0, HASH + 72, 32)
    a.hash(7, 104)
    a.cp20_fixed(ANSWER, SIGNATURE + 40)
    a.variable_header(0, 0, 0, 0)
    message_index(a, SIGNATURE, LAST_LEAF)
    a.load(6, LAST_LEAF)
    a.branch(6, 0, 'grind_done')
    a.advance(TRIAL, 1)
    a.load(6, TRIAL)
    a.li(7, 1 << 20)
    a.branch(6, 7, 'grind', True)
    a.jump('reject')
    a.label('grind_done')


def tree_parents(a: Builder, prefix: str, leaves: int, height: int, tag: int) -> None:
    a.set(LEVEL, 1)
    a.set(BASE, TREE_CACHE)
    a.set(NEXT_BASE, TREE_CACHE + 20 * leaves)
    a.set(COUNT, leaves // 2)
    a.label(prefix + '_level')
    a.set(NODE, 0)
    a.label(prefix + '_node')
    a.load(6, NODE)
    mul40(a, 10, 6)
    a.load(6, BASE)
    a.add(6, 6, 10)
    a.li(7, HASH + 40)
    a.cp20(6, 7)
    a.i(0x13, 0, 6, 6, 20)
    a.li(7, HASH + 60)
    a.cp20(6, 7)
    a.load(6, LEVEL)
    a.save(6, POS)
    a.load(6, NODE)
    a.save(6, INDEX)
    a.hash(tag, 80)
    a.load(7, NODE)
    mul20(a, 10, 7)
    a.load(7, NEXT_BASE)
    a.add(7, 7, 10)
    a.li(6, ANSWER)
    a.cp20(6, 7)
    a.advance(NODE, 1)
    a.load(6, NODE)
    a.load(7, COUNT)
    a.branch(6, 7, prefix + '_node', True)
    a.load(6, NEXT_BASE)
    a.save(6, BASE)
    a.load(7, COUNT)
    mul20(a, 10, 7)
    a.add(6, 6, 10)
    a.save(6, NEXT_BASE)
    a.load(6, COUNT)
    a.shift(6, 6, 1, True)
    a.save(6, COUNT)
    a.advance(LEVEL, 1)
    a.load(6, LEVEL)
    a.li(7, height + 1)
    a.branch(6, 7, prefix + '_level', True)


def capture_path(a: Builder, prefix: str, node_base: int,
                 leaves: int, height: int) -> None:
    a.set(PATH_BASE, node_base)
    a.set(COUNT, leaves)
    a.set(LEVEL, 0)
    a.load(6, SELECTED)
    a.save(6, BIT)
    a.label(prefix + '_path')
    a.load(6, BIT)
    a.i(0x13, 4, 6, 6, 1)  # XORI 1: sibling at this level.
    mul20(a, 10, 6)
    a.load(6, PATH_BASE)
    a.add(6, 6, 10)
    a.load(7, SIG_PTR)
    a.cp20(6, 7)
    a.advance(SIG_PTR, 20)
    a.load(6, PATH_BASE)
    a.load(7, COUNT)
    mul20(a, 10, 7)
    a.add(6, 6, 10)
    a.save(6, PATH_BASE)
    a.load(6, COUNT)
    a.shift(6, 6, 1, True)
    a.save(6, COUNT)
    a.load(6, BIT)
    a.shift(6, 6, 1, True)
    a.save(6, BIT)
    a.advance(LEVEL, 1)
    a.load(6, LEVEL)
    a.li(7, height)
    a.branch(6, 7, prefix + '_path', True)


def forest(a: Builder) -> None:
    a.set(T, 0)
    a.set(SIG_PTR, SIGNATURE + 60)
    a.label('forest_tree')
    a.load(6, T)
    a.save(6, LAYER)
    a.load(6, MSG_INDEX)
    a.save(6, TREE)
    a.li(6, LEAVES)
    a.load(7, T)
    a.add(6, 6, 7)
    a.lbu(10, 6)
    a.save(10, SELECTED)
    a.set(LEAF, 0)
    a.label('forest_leaf')
    a.set(POS, 0)
    a.load(6, LEAF)
    a.save(6, INDEX)
    a.cp(SECRET_KEY, HASH + 40, 32)
    a.hash(8, 72)
    a.cp20_fixed(ANSWER, VALUE)
    a.cp20_fixed(VALUE, HASH + 40)
    a.hash(9, 60)
    a.li(6, TREE_CACHE)
    a.load(7, LEAF)
    mul20(a, 10, 7)
    a.add(7, 6, 10)
    a.li(6, ANSWER)
    a.cp20(6, 7)
    a.advance(LEAF, 1)
    a.load(6, LEAF)
    a.li(7, 1 << FTS_HEIGHT)
    a.branch(6, 7, 'forest_leaf', True)
    tree_parents(a, 'forest', 1 << FTS_HEIGHT, FTS_HEIGHT, 10)
    a.load(6, BASE)
    a.li(7, ROOTS)
    a.load(10, T)
    mul20(a, 12, 10)
    a.add(7, 7, 12)
    a.cp20(6, 7)
    a.set(POS, 0)
    a.load(6, SELECTED)
    a.save(6, INDEX)
    a.cp(SECRET_KEY, HASH + 40, 32)
    a.hash(8, 72)
    a.cp20_to_ptr(ANSWER, SIG_PTR)
    a.advance(SIG_PTR, 20)
    capture_path(a, 'forest', TREE_CACHE, 1 << FTS_HEIGHT, FTS_HEIGHT)
    a.advance(T, 1)
    a.load(6, T)
    a.li(7, FTS_TREES)
    a.branch(6, 7, 'forest_tree', True)
    a.variable_header(0, 0, 0, 0)
    a.load(6, MSG_INDEX)
    a.save(6, TREE)
    a.cp(ROOTS, HASH + 40, 20 * FTS_TREES)
    a.hash(11, 40 + 20 * FTS_TREES)
    a.cp20_fixed(ANSWER, CURRENT)


def set_layer_address(a: Builder, number: int) -> None:
    above = sum(HEIGHTS[:number])
    below = sum(HEIGHTS[number + 1:])
    a.set(LAYER, number)
    a.load(6, MSG_INDEX)
    a.shift(6, 6, 34 - above, True)
    a.save(6, TREE)
    a.load(6, MSG_INDEX)
    a.shift(6, 6, below, True)
    a.andi(6, 6, (1 << HEIGHTS[number]) - 1)
    a.save(6, LEAF)


def ots_tree(a: Builder, number: int, offset: int) -> None:
    prefix = f'ots_tree_{number}'
    a.load(6, LEAF)
    a.save(6, SELECTED)
    a.set(LEAF, 0)
    a.label(prefix + '_leaf')
    a.set(CHAIN, 0)
    a.label(prefix + '_chain')
    a.load(6, CHAIN)
    a.save(6, POS)
    a.load(6, LEAF)
    a.save(6, INDEX)
    a.cp(SECRET_KEY, HASH + 40, 32)
    a.hash(0, 72)
    a.cp20_fixed(ANSWER, VALUE)
    a.set(STEP, 0)
    a.label(prefix + '_step')
    a.load(6, CHAIN)
    a.shift(6, 6, 3)
    a.load(7, STEP)
    a.add(6, 6, 7)
    a.save(6, POS)
    a.cp20_fixed(VALUE, HASH + 40)
    a.hash(1, 60)
    a.cp20_fixed(ANSWER, VALUE)
    a.advance(STEP, 1)
    a.load(6, STEP)
    a.li(7, 7)
    a.branch(6, 7, prefix + '_step', True)
    a.li(6, ENDPOINTS)
    a.load(7, CHAIN)
    mul20(a, 10, 7)
    a.add(7, 6, 10)
    a.li(6, VALUE)
    a.cp20(6, 7)
    a.advance(CHAIN, 1)
    a.load(6, CHAIN)
    a.li(7, CHAINS)
    a.branch(6, 7, prefix + '_chain', True)
    a.set(POS, 0)
    a.cp(ENDPOINTS, HASH + 40, 20 * CHAINS)
    a.hash(2, 40 + 20 * CHAINS)
    a.li(6, TREE_CACHE)
    a.load(7, LEAF)
    mul20(a, 10, 7)
    a.add(7, 6, 10)
    a.li(6, ANSWER)
    a.cp20(6, 7)
    a.advance(LEAF, 1)
    a.load(6, LEAF)
    a.li(7, 1 << HEIGHTS[number])
    a.branch(6, 7, prefix + '_leaf', True)
    tree_parents(a, prefix, 1 << HEIGHTS[number], HEIGHTS[number], 3)
    a.load(6, BASE)
    a.li(7, TREE_ROOT)
    a.cp20(6, 7)
    a.set(SIG_PTR, SIGNATURE + offset + 4 + 20 * CHAINS)
    capture_path(a, prefix, TREE_CACHE, 1 << HEIGHTS[number], HEIGHTS[number])
    a.load(6, SELECTED)
    a.save(6, LEAF)


def ots_sign(a: Builder, number: int, offset: int) -> None:
    prefix = f'ots_sign_{number}'
    retry = prefix + '_retry'
    a.set(COUNTER, 0)
    a.label(prefix + '_encode')
    a.set(POS, 0)
    a.load(6, LEAF)
    a.save(6, INDEX)
    a.cp20_fixed(CURRENT, HASH + 40)
    a.li(6, COUNTER)
    a.lw(10, 6)
    a.li(7, HASH)
    a.sw(10, 7, 60)
    a.hash(4, 64)
    for position in (9, 19):
        a.li(6, ANSWER)
        a.lbu(10, 6, position)
        a.andi(10, 10, 0xc0)
        okay = prefix + f'_padding_{position}'
        a.branch(10, 0, okay)
        a.jump(retry)
        a.label(okay)
    a.li(15, 0)
    for chain in range(CHAINS):
        bit = 3 * chain + (0 if chain < 26 else 2)
        position, shift = divmod(bit, 8)
        a.li(6, ANSWER)
        a.lbu(10, 6, position)
        if shift:
            a.shift(10, 10, shift, True)
        if shift > 5:
            a.lbu(12, 6, position + 1)
            a.shift(12, 12, 8 - shift)
            a.add(10, 10, 12)
        a.andi(10, 10, 7)
        a.add(15, 15, 10)
        a.li(6, DIGITS + chain)
        a.store(10, 6, byte=True)
    a.li(10, 194)
    a.branch(15, 10, prefix + '_encoded')
    a.jump(retry)
    a.label(retry)
    a.advance(COUNTER, 1)
    a.load(6, COUNTER)
    a.li(7, 1 << 20)
    a.branch(6, 7, prefix + '_encode', True)
    a.jump('reject')
    a.label(prefix + '_encoded')
    a.li(6, COUNTER)
    a.lw(10, 6)
    a.li(7, SIGNATURE + offset)
    a.sw(10, 7)
    a.set(CHAIN, 0)
    a.set(SIG_PTR, SIGNATURE + offset + 4)
    a.label(prefix + '_chain')
    a.load(6, CHAIN)
    a.save(6, POS)
    a.load(6, LEAF)
    a.save(6, INDEX)
    a.cp(SECRET_KEY, HASH + 40, 32)
    a.hash(0, 72)
    a.cp20_fixed(ANSWER, VALUE)
    a.li(6, DIGITS)
    a.load(7, CHAIN)
    a.add(6, 6, 7)
    a.lbu(10, 6)
    a.save(10, TARGET)
    a.set(STEP, 0)
    a.label(prefix + '_step')
    a.load(6, STEP)
    a.load(7, TARGET)
    a.branch(6, 7, prefix + '_chain_end')
    a.load(6, CHAIN)
    a.shift(6, 6, 3)
    a.load(7, STEP)
    a.add(6, 6, 7)
    a.save(6, POS)
    a.cp20_fixed(VALUE, HASH + 40)
    a.hash(1, 60)
    a.cp20_fixed(ANSWER, VALUE)
    a.advance(STEP, 1)
    a.jump(prefix + '_step')
    a.label(prefix + '_chain_end')
    a.cp20_to_ptr(VALUE, SIG_PTR)
    a.advance(SIG_PTR, 20)
    a.advance(CHAIN, 1)
    a.load(6, CHAIN)
    a.li(7, CHAINS)
    a.branch(6, 7, prefix + '_chain', True)


def layer_offsets() -> list[int]:
    result = [60 + FTS_TREES * (1 + FTS_HEIGHT) * 20]
    for height in HEIGHTS[:-1]:
        result.append(result[-1] + 4 + 20 * CHAINS + 20 * height)
    return result


def build_sign_prefix() -> list[int]:
    a = Builder(CACHE + 20)
    a.jump('start')
    a.label('reject')
    a.halt(False)
    a.label('start')
    prepare(a)
    grind(a)
    forest(a)
    a.halt(True)
    return a.finish()


def build_sign() -> list[int]:
    a = Builder(CACHE + 20)
    a.jump('start')
    a.label('reject')
    a.halt(False)
    a.label('start')
    prepare(a)
    grind(a)
    forest(a)
    offsets = layer_offsets()
    for number in reversed(range(len(HEIGHTS))):
        set_layer_address(a, number)
        if number:
            ots_tree(a, number, offsets[number])
            ots_sign(a, number, offsets[number])
            a.cp20_fixed(TREE_ROOT, CURRENT)
        else:
            ots_sign(a, number, offsets[number])
            a.load(6, LEAF)
            a.save(6, SELECTED)
            a.set(SIG_PTR, SIGNATURE + offsets[number] + 4 + 20 * CHAINS)
            capture_path(a, 'top', CACHE + 40, 1 << HEIGHTS[0], HEIGHTS[0])
            layer(a, 0, offsets[number], SIGNATURE)
            a.compare20(CURRENT, CACHE)
    a.halt(True)
    build_sign.labels = a.labels
    return a.finish()


if __name__ == '__main__':
    print('prefix:', len(build_sign_prefix()), 'instructions')
    print('sign:', len(build_sign()), 'instructions')
